name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Deploy to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no your_user@your_vm_ip "
        cd /path/to/your/app &&
        git pull origin main &&
        docker-compose down &&
        docker-compose up -d --build
        "
