name: salry-microservice

'on': push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Update Java version
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'
         
        - name: install the gcloud cli
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GOOGLE_PROJECT }}
            service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            export_default_credentials: true

        - name: First build
          env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          run: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            make docker-build
            make docker-push

        - name: testing
          run: |
            make fmt
            make test
            mvn checkstyle:checkstyle
            mvn test

