name: salary-microservice

'on': push

jobs:
    build:
        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        # - name: maven version-check
          # run: mvn -version

        - name: Update Java version
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '17'
         
        - name: install the gcloud cli
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GOOGLE_PROJECT }}
            service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            export_default_credentials: true

        - name: First build
          env:
            GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          run: |
            gcloud auth configure-docker us-central1-docker.pkg.dev
            make docker-build
            make docker-push

        - name: make-fmt
          run: make fmt

        - name: make-test
          run: make test
            
        - name: mvn-check-style
          run: mvn checkstyle:checkstyle

        - name: mvn-test
          run: mvn test

        - name: migration
          run: make run-migrations

        - name: app access
          run: java -jar target/salary-0.1.0-RELEASE.jar


