# name: salary-action-tests

# 'on':
#     pull_request:
#       types: [opened]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: print date
#         run: date

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Update Java version
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin' 
      #     java-version: '17'

      # # - name: List files
      # #   run: ls -lrth

      # # - name: First build
      # #   run: make build

      # - name: build
      #   run: mvn clean package



name: PR Review Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: print date
      run: date

    - name: Leave PR Review with Feedback
      uses: actions/github-script@v6
      with:
        script: |
          const { GITHUB_TOKEN } = process.env;
          const { owner, repo, number: pull_number } = context.issue;

          const reviewBody = "Automated feedback: Please check the current date and time";

          await github.pulls.createReview({
            owner,
            repo,
            pull_number,
            event: "REQUEST_CHANGES", # or "COMMENT", "APPROVE"
            body: reviewBody,
          });
