name: salary-action-tests

'on': push
    # schedule:
    #   - cron: '25 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Update Java version
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin' 
      #     java-version: '17'

      # - name: List files
      #   run: ls -lrth

      # - name: First build
      #   run: make build

      - name: build
        run: mvn clean package
